[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/rankings"
  to = "/rankings.html"
  status = 200

[[redirects]]
  from = "/haste"
  to = "/haste.html"
  status = 200

[[redirects]]
  from = "/addons"
  to = "/addons.html"
  status = 200

[[redirects]]
  from = "/guide"
  to = "/guide.html"
  status = 200
